[package]
name = "tonk-web-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
dotenv = "0.15.0"
serde = { version = "1.0.188", features = ["derive"] }
tonk-shared-lib = { path = "../tonk-shared-lib" }
redis = { version = "0.23.3", features = [ "json", "aio", "tokio-comp" ] }
bincode = { version = "2.0.0-rc.3" }
futures = "0.3.28"
rand = "0.8.5"
ethers-rs = "0.2.3"
