[package]
name = "tonk-shared-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.3" }
serde = { version = "1.0.188", features = ["derive"] }
redis = { version = "0.23.3", features = [ "json", "aio", "tokio-comp" ] }
tokio = { version = "1.32.0", features = [ "sync" ] }

